version: '3.8'

services:
  bike-inventory:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bike-inventory
    ports:
      - "${STREAMLIT_SERVER_PORT:-8501}:8501"
    volumes:
      # Mount the database and images directory for persistence
      - bike_data:/app/static/images
      - bike_db:/app
    environment:
      - TZ=${TZ:-Europe/Berlin}
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=${STREAMLIT_BROWSER_GATHER_USAGE_STATS:-false}
      - STREAMLIT_THEME_PRIMARY_COLOR=${STREAMLIT_THEME_PRIMARY_COLOR:-#FF4B4B}
    restart: always
    networks:
      - bike_network
    # Add resource limits to ensure stability
    deploy:
      resources:
        limits:
          cpus: '${DOCKER_LIMIT_CPU:-1}'
          memory: ${DOCKER_LIMIT_MEMORY:-1G}
        reservations:
          cpus: '${DOCKER_RESERVE_CPU:-0.25}'
          memory: ${DOCKER_RESERVE_MEMORY:-512M}
    # Add healthcheck to ensure application is running
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add Watchtower for automatic updates
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 86400 --cleanup  # Check for updates once per day
    restart: always
    environment:
      - TZ=Europe/Berlin  # Set your timezone
    depends_on:
      - bike-inventory

volumes:
  bike_data:
    name: bike_inventory_images
  bike_db:
    name: bike_inventory_db

networks:
  bike_network:
    name: bike_inventory_network
    driver: bridge
