version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
    ports:
      - "4000:4000"
  frontend:
    build: ./frontend
    ports:
      - "443:443"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=https://localhost:4000
    volumes:
      - ./frontend/public/cert:/usr/src/app/public/cert
