version: '3.8'

# This override file is for development purposes
# Usage: docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d

services:
  bike-inventory:
    # Mount code directory for live code changes during development
    volumes:
      - .:/app
      # Exclude node_modules and other large directories
      - /app/__pycache__
    environment:
      - DEBUG=true
      - STREAMLIT_SERVER_RUN_ON_SAVE=true
    # Use the development command with auto-reload
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0 --server.runOnSave=true --server.enableCORS=false --server.enableXsrfProtection=false
